# This workflow helps ensure that the code of the action we're going to deploy:
# 1. Is well-formated
# 2. Is linted

name: Linting

on:
  workflow_call:
    inputs:
      requirements_file_path:
        description: "Path of the project dependencies file"
        default: ""
        required: false
        type: string
        
      toml_config_file_path:
        description: "Path of the configuration file for Black, isort and Pylint"
        default: ""
        required: false
        type: string
    
jobs:
  run-pylint:
    runs-on: ubuntu-latest
    name: pylint
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        if [-n "${{ inputs.requirements_file_path }}"]
        then
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements_file_path }}
        else
          echo "No dependencies file provided"
        fi
    
    - name: Analysing the code with pylint
      run: |
        if [-n "${{ inputs.toml_config_file_path }}"]
        then
          pylint --rcfile ${{ inputs.toml_config_file_path }} $(git ls-files '*.py')
        else
          pylint $(git ls-files '*.py')

  run-isort:
    runs-on: ubuntu-latest
    name: isort
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: isort/isort-action@master
      with:
          requirementsFiles: ${{ inputs.requirements_file_path }}

  run-black:
    runs-on: ubuntu-latest
    name: black
    steps:
    - uses: actions/checkout@v3    
    - uses: psf/black@stable
      with:
        options: "--check --verbose"
