name: Formatting/Linting

on:
  workflow_call:
    inputs:
      requirements_file_path:
        required: true
        type: string
      
      toml_config_file_path:
        required: true
        type: string
    
jobs:
  run-pylint:
    runs-on: ubuntu-latest
    name: pylint
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{inputs.requirements_file_path}}
    
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile ${{inputs.toml_config_file_path}} $(git ls-files '*.py')

  run-isort:
    runs-on: ubuntu-latest
    name: isort
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: isort/isort-action@master
      with:
          requirementsFiles: ${{inputs.requirements_file_path}}

  run-black:
    runs-on: ubuntu-latest
    name: black
    steps:
    - uses: actions/checkout@v3    
    - uses: psf/black@stable
      with:
        options: "--check --verbose"
