# This workflow helps ensure that our code:
# 1. Is well-formated
# 2. Is linted

name: Format & Lint

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: false
        default: "3.9"

      requirements_file_path:
        description: "Path of the project dependencies file"
        type: string
        required: false
        default: ""
        
      toml_config_file_path:
        description: "Path of the configuration file for Black, isort and Pylint"
        type: string
        required: false
        default: ""
    
jobs:
  run-pylint:
    runs-on: ubuntu-latest
    name: pylint
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Install dependencies
      run: |
        if [ -f "${{ inputs.requirements_file_path }}" ]
        then
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements_file_path }}
        else
          python -m pip install --upgrade pip
          pip install pylint        
          echo "No dependencies file provided"
        fi
    
    - name: Analysing the code with pylint
      run: |
        if [ -f "${{ inputs.toml_config_file_path }}" ]
        then
          pylint --rcfile ${{ inputs.toml_config_file_path }} $(git ls-files '*.py')
        else
          pylint $(git ls-files '*.py')
        fi

  run-isort:
    runs-on: ubuntu-latest
    name: isort
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - uses: isort/isort-action@master
      with:
          requirementsFiles: ${{ inputs.requirements_file_path }}

  run-black:
    runs-on: ubuntu-latest
    name: black
    steps:
    - uses: actions/checkout@v3    
    - uses: psf/black@stable
      with:
        options: "--check --verbose"
